[package]
name = "clap_derive-app"
version = "0.1.0"
authors = ["Evgeniy Reizner <razrfalcon@gmail.com>"]
edition = "2018"

[[bin]]
name = "clap_derive-app"
path = "app.rs"

[dependencies]
clap = { version = "4.4.6", features = ["derive"] }
