[package]
name = "pico-args-app"
edition.workspace = true

[[bin]]
name = "pico-args-app"
path = "app.rs"

[dependencies]
pico-args = "0.5"

[features]
default = ["eq-separator"]
eq-separator = ["pico-args/eq-separator"]
